name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: echo a string
        run: echo "hello world"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: multiline
        run: |
          node -v
          npm -v
      - name: run on python shell
      - uses: actions/setup-python@v4
        with:
          python-version: "3.5" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
        run: |
          import platform
          print (platform.processor())
        shell: python
      - name: detect number of processer
        run: cat ../../processor.py
  # run-windows-command:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Directory Shell
  #       run: Get-Location
