name: Using Action

on:
  schedule:
    - cron: "1 * * * *"
  pull_request:
    type: [closed, completed, reopened]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: list directory
        run: ls -lha
      - name: simple nodejs action
        id: first_step
        uses: actions/hello-world-javascript-action@ab59b778e5d5349998ed92edbc168703d3a66512
        with:
          who-to-greet: "MOca"
      - name: logs Greetins
        run: echo "${{ steps.first_step.outputs.time }}"
      - name: github default variable
        run: |
          echo "Github sha: $GITHUB_SHA"
          echo "Github repository: $GITHUB_REPOSITORY"
          echo "Github workspace: $GITHUB_WORKSPACE"
