name: Using Action

on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      - name: list directory
        run: ls -lha
